# Generated by Django 5.0.3 on 2024-03-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_phone_member_vehiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='nombre',
        ),
    ]
