# Generated by Django 5.0.3 on 2024-03-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_firstname_member_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
    ]
