# Generated by Django 5.0.3 on 2024-03-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='vehiculo',
            field=models.CharField(max_length=255),
        ),
    ]
