# Generated by Django 5.0.3 on 2024-03-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='reparacion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
